jpa:
  properties:
    hibernate:
      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
      # dialect: org.hibernate.dialect.H2Dialect

      format_sql : true
      id:
        new_generator_mappings: false


  hibernate:

  ddl-auto: create   #update,,drop,create-drop
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5Dialect
datasource:
  url: jdbc:mysql://localhost:3306/employees?createDatabaseIfNotExist=true
  username: root
  password:
  main:
    allow-bean-definition-overriding : true
